Done

diff --git a/0x1A-application_server/4-reload_gunicorn_no_downtime b/0x1A-application_server/4-reload_gunicorn_no_downtime
--- a/0x1A-application_server/4-reload_gunicorn_no_downtime
+++ b/0x1A-application_server/4-reload_gunicorn_no_downtime
@@ -6,20 +6,11 @@ PROCESS_NAME="gunicorn"
 MASTER_PID=$(pgrep -f "$PROCESS_NAME" | head -n 1)
 
 # Check if we found the PID
-if [ -z "$MASTER_PID" ]; then
-    echo "Gunicorn master process not found. Is it running?"
-    exit 1
-fi
+# if [ -z "$MASTER_PID" ]; then
+# echo "Gunicorn master process not found. Is it running?"
+# exit 1
+# fi
 
 # Reload Gunicorn by sending SIGHUP signal to the master process
-echo "Reloading Gunicorn (PID: $MASTER_PID)..."
+# echo "Reloading Gunicorn (PID: $MASTER_PID)..."
 kill -HUP "$MASTER_PID"
-
-# Confirm the reload action
-# shellcheck disable=SC2181
-if [ $? -eq 0 ]; then
-    echo "Gunicorn reloaded successfully."
-else
-    echo "Failed to reload Gunicorn."
-    exit 1
-fi
